### ISSUE TITLE
RDKE-115: SSH not working for RDKE builds

### ISSUE THREAD

**Issue by leenaS-d** [rdkcentral/meta-vendor-raspberrypi-release#20]
Integrate dropbear and required configs

**Comment by arun-madhavan-013** [comment]
Vendor pacakge-group is not supposed to have dropbear.
But https://github.com/rdkcentral/meta-vendor-raspberrypi-dev/commit/47ed7a3ce3a4e16d146ec29fea2f2ed8b3bddd71 adds SSH support in vendor test image.
